# Generated by Django 5.0.1 on 2024-01-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst_poster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Аккаунт Instagram',
                'verbose_name_plural': 'Аккаунты Instagram',
            },
        ),
        migrations.RemoveField(
            model_name='mailcredentials',
            name='owner',
        ),
        migrations.AlterModelOptions(
            name='instphotos',
            options={'verbose_name': 'Изображение и подпись', 'verbose_name_plural': 'Изображения и подписи'},
        ),
        migrations.AlterModelOptions(
            name='proxycredentials',
            options={'verbose_name': 'Настройки прокси', 'verbose_name_plural': 'Настройки прокси'},
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name': 'Результаты', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.DeleteModel(
            name='InstCredentials',
        ),
        migrations.DeleteModel(
            name='MailCredentials',
        ),
    ]
