# Generated by Django 5.0.1 on 2024-01-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst_poster', '0002_credentials_remove_mailcredentials_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instphotos',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proxycredentials',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
