# Generated by Django 5.0.1 on 2024-01-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst_poster', '0003_credentials_timestamp_instphotos_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_inst', models.CharField(max_length=100)),
                ('pass_inst', models.CharField(max_length=100)),
                ('login_mail', models.CharField(max_length=100)),
                ('pass_mail', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Аккаунт Instagram',
                'verbose_name_plural': 'Аккаунты Instagram',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Credentials',
        ),
        migrations.AlterModelOptions(
            name='instphotos',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Изображение и подпись', 'verbose_name_plural': 'Изображения и подписи'},
        ),
        migrations.AlterModelOptions(
            name='proxycredentials',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Настройки прокси', 'verbose_name_plural': 'Настройки прокси'},
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Результаты', 'verbose_name_plural': 'Результаты'},
        ),
    ]
