# Generated by Django 5.0.1 on 2024-01-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst_poster', '0004_datacredentials_delete_credentials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacredentials',
            name='timestampp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
