# Generated by Django 5.0.1 on 2024-01-25 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst_poster', '0007_rename_good_links_results_good_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Категории фото')),
            ],
            options={
                'verbose_name': 'Категории фото',
                'verbose_name_plural': 'Категории фото',
            },
        ),
        migrations.RemoveField(
            model_name='datacredentials',
            name='timestampp',
        ),
        migrations.AlterField(
            model_name='datacredentials',
            name='login_mail',
            field=models.CharField(blank=True, max_length=100, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='datacredentials',
            name='pass_mail',
            field=models.CharField(blank=True, max_length=100, verbose_name='Пароль от почты'),
        ),
        migrations.AlterField(
            model_name='datacredentials',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='results',
            name='good_link',
            field=models.CharField(max_length=100, verbose_name='Ссылка на пост'),
        ),
        migrations.AlterField(
            model_name='results',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата поста'),
        ),
        migrations.AddField(
            model_name='instphotos',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inst_poster.category'),
            preserve_default=False,
        ),
    ]
