# Generated by Django 5.0.1 on 2024-01-25 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst_poster', '0009_alter_instphotos_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию фото', 'verbose_name_plural': 'Категории фото'},
        ),
        migrations.RemoveField(
            model_name='instphotos',
            name='photo_caption',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Категория фото'),
        ),
        migrations.AlterField(
            model_name='instphotos',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inst_poster.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Captions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(max_length=70000)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inst_poster.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категорию фото',
                'verbose_name_plural': 'Категории фото',
            },
        ),
    ]
